package com.github.exception;

/**
 * @ Author: 瞎驴
 * @ description: 自己手动抛出异常
 * @ Date: 2019/5/7 23:41
 * @ Version 1.0
 */
public class Demo_throwException {
    public static void main(String[] args) throws Exception {
        Person p = new Person();
        p.setAge(0);
    }
}
